citrusframework/yaks

- .gitignore
- examples/http.feature
- java/pom.xml
- java/yaks-testing-http/pom.xml
- java/yaks-testing-http/src/main/java/dev/yaks/testing/http/HttpConfiguration.java
- java/yaks-testing/src/main/resources/citrus-application.properties
The http example needs a default http client in Citrus Spring application context. Also introduced a new testing-http module where we can add some more advanced Http steps.
One day these Http steps can be moved to Citrus but for now it should be easier to develop here.
> fix: Http example

- .gitignore
- Makefile
- README.md
- build/Dockerfile
- build/bin/entrypoint
- cmd/manager/main.go
- deploy/operator.yaml
- deploy/resources.go
- hack/clean.sh
- hack/cross_compile.sh
- pkg/cmd/install.go
- pkg/cmd/operator.go
- pkg/cmd/operator/operator.go
- pkg/cmd/root.go
- pkg/cmd/test.go
- pkg/cmd/util.go
Now `yaks operator` runs the operator (used only internally inside openshift), so there's now a single binary file.
I've added the release command and released docker.io/yaks/yaks:0.0.1 (send me your docker hub id to be added to the docker org and run the releases yourself).
Added cross-compilation. Binaries need to be uploaded manually to [github releases](https://github.com/jboss-fuse/yaks/releases).
assign: @lburgazzoli, @christophd, @jamesnetherton
> Fix #8: unify yaks and yaks-cli and add release scripts

- java/pom.xml
- java/yaks-testing-jdbc/pom.xml
- java/yaks-testing-jdbc/src/main/java/dev/yaks/testing/jdbc/JdbcSteps.java
- java/yaks-testing/src/main/java/dev/yaks/testing/TestRunner.java
This PR adds JDBC verification Cucumber steps. These can be used in a feature scenario to access the DB and verify SQL result sets:
```
Feature: JDBC connectitiy
Background:
Given Database connection
| url       | jdbc:postgresql://localhost:5432/sampledb |
| username  | sampledb |
| password  | ***** |
Scenario: INSERT task
Given variables
| todoId  | citrus:randomNumber(4) |
| task    | Test CamelK with YAKS! |
Then SQL update: INSERT INTO todo (id, task, completed) VALUES (${todoId}, '${task}', 0)
Scenario: SELECT and verify task
Given variable taskId is "citrus:randomNumber(10)"
When SQL query: SELECT COUNT(task) AS FOUND_TASKS FROM todo WHERE task='Task #${taskId}'
Then verify column FOUND_TASKS=1
```
Also supported multiple SQL statements:
```
Given SQL updates 
| INSERT INTO todo …
```
> #4 First version of JDBC verification steps

- deploy/olm-catalog/csv-config.yaml
- deploy/olm-catalog/yaks/0.0.1/yaks.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/yaks/0.0.1/yaks_v1alpha1_test_crd.yaml
- deploy/olm-catalog/yaks/yaks.package.yaml
Here's an initial stab at a CSV for YAKS.
I did my best with the wording for the descriptions & examples. Since this is just a POC, for now I chose some arbitrary values for fields like `support` / `provider` / `categories` and commented out `maintainer`, until we have a better idea of what those values will be.
I created a YAKS organization on quay.io. If anyone would like admin access to it, let me know your user id.
To see YAKS show up in OpenShift create an `operatorsource`:
```
apiVersion: operators.coreos.com/v1
kind: OperatorSource
metadata:
name: yaks
namespace: openshift-marketplace
spec:
type: appregistry
endpoint: https://quay.io/cnr
registryNamespace: yaks
displayName: "YAKS Operators"
publisher: "Red Hat"
```
Then after a short time, the operator should show up.
> Fix #6. Create a CSV for Operator Marketplace

- pkg/controller/test/start.go
So user can delete all terminated pods and config maps with
```
oc delete all -l yaks.dev/app=yaks
```
> chore: Use application wide label to mark all yaks resources

- .envrc
- .gitignore
- README.md
- build/Dockerfile
- pkg/config/config.go
- pkg/controller/test/start.go
This adds the possibility to add custom steps as defined in https://github.com/nicolaferraro/yaks-extension
In order for this to work, we need to refresh the yaks:yaks:0.0.1 image with latest changes (which I'll do after merge).
> Add possibility to plug External steps

- java/yaks-testing/src/main/java/dev/yaks/testing/TestReporter.java
- java/yaks-testing/src/main/java/dev/yaks/testing/TestRunner.java
- java/yaks-testing/src/test/java/dev/yaks/testing/ReportSetupHook.java
- java/yaks-testing/src/test/java/dev/yaks/testing/ReportVerifyPlugin.java
- java/yaks-testing/src/test/java/dev/yaks/testing/ReporterTest.java
- java/yaks-testing/src/test/resources/cucumber.properties
- java/yaks-testing/src/test/resources/dev/yaks/testing/report.feature
- pkg/controller/test/start.go
… as container status message
You can see the custom termination logs when doing
`oc get pod test-jdbc-bleip0t8kplsnet62e50 -o yaml`
You will get the test failure cause as container termination message.
```yaml
state:
terminated:
containerID: docker://e0d425746d82d66ba464c3c106269b1157d3cb94616d4a3acac90f4bdc4a364d
exitCode: 1
finishedAt: 2019-08-21T11:35:37Z
message: |
/etc/yaks/test/..2019_08_21_11_35_31.525541819/jdbc.feature:9 FAILED - Caused by: com.consol.citrus.exceptions.CitrusRuntimeException: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.postgresql.util.PSQLException: FATAL: password authentication failed for user "sampledb"
/etc/yaks/test/..2019_08_21_11_35_31.525541819/jdbc.feature:17 FAILED - Caused by: …
```
> feat: Write custom termination logs so test failure cause is reported

- java/pom.xml
- java/yaks-testing-camel/pom.xml
- java/yaks-testing-camel/src/main/java/dev/yaks/testing/camel/CamelSteps.java
- java/yaks-testing-camel/src/test/java/dev/yaks/testing/camel/CamelFeatureTest.java
- java/yaks-testing-camel/src/test/resources/cucumber.properties
- java/yaks-testing-camel/src/test/resources/dev/yaks/testing/camel/camel-context.feature
- java/yaks-testing-camel/src/test/resources/dev/yaks/testing/camel/camel-route-groovy.feature
- java/yaks-testing-camel/src/test/resources/dev/yaks/testing/camel/camel-route-xml.feature
- java/yaks-testing-camel/src/test/resources/log4j2-test.xml
Fixes #30 
PR enables us to create Camel routes as part of the test.
```gherkin
Given Camel route hello.groovy
"""
from("direct:hello")
.to("log:dev.yaks.testing.camel?level=INFO")
.split(body().tokenize(" "))
.to("seda:tokens")
.end()
"""
```
Right now supports XML and Groovy route definitions. In future we might want to reuse the camel-k-runtime route loader implementations for all languages (Yaml, Groovy, JavaScript, ...). 
But before we can do that we need to align the same Camel versions (CamelK runtime uses 3.0.0.M3, Citrus 2.21.1)
> feat: Add Camel route steps

- java/pom.xml
- java/yaks-testing-http/src/main/java/dev/yaks/testing/http/HttpClientSteps.java
- java/yaks-testing-http/src/main/java/dev/yaks/testing/http/HttpServerSteps.java
- java/yaks-testing-http/src/main/java/dev/yaks/testing/http/HttpSteps.java
- java/yaks-testing-swagger/pom.xml
- java/yaks-testing-swagger/src/main/java/dev/yaks/testing/swagger/SwaggerResourceLoader.java
- java/yaks-testing-swagger/src/main/java/dev/yaks/testing/swagger/SwaggerSteps.java
- java/yaks-testing-swagger/src/main/java/dev/yaks/testing/swagger/SwaggerTestDataGenerator.java
- java/yaks-testing-swagger/src/test/java/dev/yaks/testing/swagger/PetstoreConfiguration.java
- java/yaks-testing-swagger/src/test/java/dev/yaks/testing/swagger/SwaggerFeatureTest.java
- java/yaks-testing-swagger/src/test/resources/citrus-application.properties
- java/yaks-testing-swagger/src/test/resources/cucumber.properties
- java/yaks-testing-swagger/src/test/resources/dev/yaks/testing/swagger/pet.json
- java/yaks-testing-swagger/src/test/resources/dev/yaks/testing/swagger/petstore-api.json
- java/yaks-testing-swagger/src/test/resources/dev/yaks/testing/swagger/petstore-open-api.feature
- java/yaks-testing-swagger/src/test/resources/dev/yaks/testing/swagger/petstore-rest-api.feature
- java/yaks-testing-swagger/src/test/resources/log4j2-test.xml
- java/yaks-testing/src/main/java/dev/yaks/testing/TestRunner.java
Adds Open API support on generating test data for Http scenarios. Also reduces code duplications on HttpSteps.
Fixes #32
> feat: #32 Add Swagger steps

- java/yaks-testing/src/main/java/dev/yaks/testing/TestRunner.java
This enables the user to use the camel steps out of the box
> fix: Missing camel steps as glue in test runner

- java/yaks-testing-swagger/src/main/java/dev/yaks/testing/swagger/SwaggerTestDataGenerator.java
Make sure generated numbers are compliant with int32 format
> fix: Generate numbers from Swagger compliant with integer boundaries

- java/pom.xml
- java/yaks-testing-camel/pom.xml
Spring 4.x and 5.x libs were mixed because of older Camel version bringing in Spring 4.x. Fixed by upgrading the Camel version and pin Spring version to the one compatible with Citrus.
> fix[ENTESB-12609]: Spring major version conflicts

- pkg/cmd/test.go
> fix[ENTESB-12540]: #41 Fix test execution when no settings file is provided

- cmd/manager/main.go
- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/cmd/test.go
This should also check if the CI/CD works.. it should trigger a new release with patch version increased.
> fix: return non-zero exit code when test fails

- java/pom.xml
- java/steps/yaks-jms/pom.xml
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/JmsSteps.java
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/connection/ConnectionFactoryCreator.java
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/connection/DefaultConnectionFactoryCreator.java
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/connection/activemq/ActiveMQConnectionFactoryCreator.java
- java/steps/yaks-jms/src/main/resources/META-INF/services/org.citrusframework.yaks.jms.connection.ConnectionFactoryCreator
- java/steps/yaks-jms/src/test/java/org/citrusframework/yaks/jms/connection/ConnectionFactoryCreatorTest.java
- java/steps/yaks-jms/src/test/java/org/citrusframework/yaks/jms/connection/DefaultConnectionFactoryCreatorTest.java
- java/steps/yaks-jms/src/test/java/org/citrusframework/yaks/jms/connection/activemq/ActiveMQConnectionFactoryCreatorTest.java
- java/steps/yaks-jms/src/test/resources/org/citrusframework/yaks/jms/jms.feature
- java/steps/yaks-kafka/pom.xml
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSteps.java
- java/steps/yaks-kafka/src/test/java/org/citrusframework/yaks/kafka/EmbeddedKafkaConfiguration.java
- java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka.feature
Refactor JMS connection factory creation with dedicated helpers that map user provided connection properties to connection factory constructor arguments or setter methods. At the moment provide ActiveMQ connection factory support. By default try to set the constructor arguments on the connection factory with given order by user.
Also add multiline body steps for JMS and Kafka and fix obsolete citrus-java-dsl dependency in Maven POMs.
Fixes #66
> fix[#66]: Improve JMS connection factory instantiation

- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/connection/activemq/ActiveMQConnectionFactoryCreator.java
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/connection/activemq/artemis/ActiveMQArtemisConnectionFactoryCreator.java
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSteps.java
- java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka-multiline.feature
Kafka endpoints may need to use different consumer groups in order to not run into message timeouts when multiple consumers use the same group.
> chore: Add Kafka consumer group setting

- java/steps/yaks-camel-k/pom.xml
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKHelper.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSettings.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSteps.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/CreateIntegrationTestAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/VerifyIntegrationTestAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/Integration.java
- Using Citrus test actions in order to support test variables, functions and other Citrus features within CamelK steps
- Add "should not print" to verify that a log message is not present
Fixes #78
> fix(#78): Refactor CamelK steps

- README.md
- examples/run-scripts/finish.sh
- examples/run-scripts/prepare.sh
- examples/run-scripts/test.feature
- examples/run-scripts/yaks-config.yaml
- pkg/cmd/config/config.go
- pkg/cmd/test.go
You can run scripts before/after a test group. Just add your commands to the `yaks-config.yaml` configuration for the test group.
```yaml
config:
namespace:
temporary: false
autoRemove: true
pre:
- script: prepare.sh
- run: echo Start!
post:
- script: finish.sh
- run: echo Bye!
```
The section `pre` runs before a test group and `post` is added after the test group has finished. The post steps are run even if the tests or pre steps fail
for some reason. This ensures that cleanup tasks are performed also in case of errors. 
The `script` option provides a file path to bash script to execute. The user has to make sure that the script is executable. If no absolute file path is 
given it is assumed to be a file path relative to the current test group directory.
With `run` you can add any shell …
> fix(#60): Add possibility to run scripts before/after a test group

- README.md
- pkg/cmd/test.go
This contains some improvements for the CLI:
- support for multiline scripts in run
- injection of the YAKS_NAMESPACE environment variable
- using a consistent base dir for the script
> Yaks CLI fixes

- .gitignore
- README.md
- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/apis/yaks/v1alpha1/zz_generated.deepcopy.go
- pkg/cmd/install.go
- pkg/cmd/report.go
- pkg/cmd/report/junit.go
- pkg/cmd/report/report.go
- pkg/cmd/report/util.go
- pkg/cmd/root.go
- pkg/cmd/test.go
- pkg/controller/test/evaluate.go
- pkg/controller/test/initialize.go
- pkg/controller/test/monitor.go
- Auto save test results in json format for each test executed to local output dir
- Add new YAKS cli command 'report'
- Add report option to fetch test results from cluster
- Generate report from test results supporting different output formats (junit, json, summary)
Also added a fix for temporary namespace usage in combination with test command options
When test cli command used some options (like --upload) in combination with running the test in a temporary namespace errors were reported due to the fact that those cli options were forwarded to the install command. Now avoiding to forward the cli options to the install command when setting up cluster and operator on the temporary namespace
> fix(ENTESB-13151): Add test report generation

- pkg/cmd/test.go
- remove `scriptFile = path.Join(baseDir, step.Script)` since we set baseDir on https://github.com/citrusframework/yaks/blob/master/pkg/cmd/test.go#L587
- redirect command stderr to stdout see what went wrong during command execution
> Fix script

- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
- java/steps/yaks-http/src/test/resources/org/citrusframework/yaks/http/http.client.feature
- java/steps/yaks-standard/pom.xml
- java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/hooks/InjectEnvVarsHook.java
- java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/hooks/InjectEnvVarsHookTest.java
- java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/standard/StandardFeatureTest.java
- pkg/cmd/test.go
> fix(#90): Inject environment variables as test variables before scenario

- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
- java/steps/yaks-http/src/test/java/org/citrusframework/yaks/http/HttpEndpointConfiguration.java
- java/steps/yaks-http/src/test/resources/org/citrusframework/yaks/http/http.client.feature
Add step to wait for a given URL to return a Http status. This implements a sort of health check on a given endpoint URL. The wait step polls on the endpoint URL with a given interval. Users can set the basic Http request timeout in milliseconds.
Sample usage in a feature:
```gherkin
Background:
Given variable port is "8080"
Given URL: http://localhost:${port}
Scenario: Health check
And URL is healthy
Scenario: Wait for Http URL condition
Given HTTP request timeout is 5000 milliseconds
Then wait for URL http://localhost:${port}/todo to return 200 OK
And wait for GET on URL http://localhost:${port}/todo
```
> fix(#92): Add waitFor Http URL condition step

- README.md
- examples/jitpack/jitpack.feature
- examples/jitpack/yaks-config.yaml
- examples/jitpack/yaks.settings.yaml
- examples/yaks.properties
- examples/yaks.settings.json
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ExtensionSettings.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ProjectModelEnricher.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ProjectModelReader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/AbstractConfigFileRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/FileBasedRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/RepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/env/EnvironmentSettingRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/json/JsonFileRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/properties/PropertyFileRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/properties/SystemPropertyRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/yaml/YamlFileRepositoryLoader.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/FileBasedRepositoryLoaderTest.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/TestHelper.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/env/EnvironmentSettingRepositoryLoaderTest.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/json/JsonFileRepositoryLoaderTest.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/properties/PropertyFileRepositoryLoaderTest.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/properties/SystemPropertyRepositoryLoaderTest.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/yaml/YamlFileRepositoryLoaderTest.java
- java/tools/maven/yaks-maven-extension/src/test/resources/yaks.properties
- java/tools/maven/yaks-maven-extension/src/test/resources/yaks.settings.json
- java/tools/maven/yaks-maven-extension/src/test/resources/yaks.settings.yaml
- pkg/cmd/config/config.go
- pkg/cmd/test.go
- pkg/controller/test/start.go
Users may add custom Maven repository configuration (id, url) via 'maven-repository' CLI option, settings file, system properties or environment variables. This way we can also include jitpack.io for custom steps.
Heads-Up this PR also renamed setting `autoremove` to `autoRemove`
Fixes #75  
Fixes #82
> fix(#75): Support custom Maven repository configuration

- README.md
- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpServerSteps.java
- java/steps/yaks-http/src/test/resources/org/citrusframework/yaks/http/http.client.feature
- Support both full request URL and relative resource path when doing a Http health check
- Add Http steps documentation to README
- Fix http-server and http-client step wording to be compliant with other steps
- Add "HTTP server listening on port {port}" step to create new server instance
Fixes #101
> fix(#101): Wait for Http resource path

- java/pom.xml
- java/runtime/yaks-runtime-maven/pom.xml
- java/steps/yaks-camel-k/pom.xml
- java/steps/yaks-camel/pom.xml
- java/steps/yaks-http/pom.xml
- java/steps/yaks-http/src/test/resources/citrus-application.properties
- java/steps/yaks-jdbc/pom.xml
- java/steps/yaks-jdbc/src/main/java/org/citrusframework/yaks/jdbc/JdbcSteps.java
- java/steps/yaks-jdbc/src/test/java/org/citrusframework/yaks/jdbc/JdbcStepsTest.java
- java/steps/yaks-jms/pom.xml
- java/steps/yaks-kafka/pom.xml
- java/steps/yaks-openapi/pom.xml
- java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/OpenApiSteps.java
- java/steps/yaks-openapi/src/test/resources/citrus-application.properties
- java/steps/yaks-standard/pom.xml
- java/tools/maven/yaks-maven-extension/pom.xml
Only depend on those Citrus modules that we really need at runtime. Other dependencies will be added to the individual test configurations. This makes the YAKS image smaller and avoids that unused modules are loaded at startup.
> chore: Reduce 3rd party dependencies

- pkg/cmd/test.go
10 minutes timeout to pass the test could not be enough.
> Increase test timeout

- java/runtime/yaks-runtime-maven/src/test/java/org/citrusframework/yaks/YaksTest.java
- java/steps/yaks-camel/src/main/java/org/citrusframework/yaks/camel/CamelSteps.java
- java/steps/yaks-http/pom.xml
- java/steps/yaks-http/src/test/java/org/citrusframework/yaks/http/HttpFeatureTest.java
- java/steps/yaks-jdbc/pom.xml
- java/steps/yaks-jdbc/src/test/java/org/citrusframework/yaks/jdbc/JdbcStepsTest.java
- java/steps/yaks-jms/pom.xml
- java/steps/yaks-jms/src/test/java/org/citrusframework/yaks/jms/JmsFeatureTest.java
- java/steps/yaks-kafka/pom.xml
- java/steps/yaks-kafka/src/test/java/org/citrusframework/yaks/kafka/KafkaFeatureTest.java
- java/steps/yaks-knative/src/test/java/org/citrusframework/yaks/knative/KnativeFeatureTest.java
- java/steps/yaks-openapi/pom.xml
- java/steps/yaks-openapi/src/test/java/org/citrusframework/yaks/openapi/OpenApiFeatureTest.java
- java/steps/yaks-standard/pom.xml
- java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/ComponentSteps.java
- java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/MessagingSteps.java
- java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/StandardSteps.java
- java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/report/ReporterTest.java
- java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/standard/EndpointConfiguration.java
- java/steps/yaks-standard/src/test/resources/citrus-application.properties
- java/steps/yaks-standard/src/test/resources/org/citrusframework/yaks/report/report.feature
- java/steps/yaks-standard/src/test/resources/org/citrusframework/yaks/standard/helloworld.feature
- java/steps/yaks-standard/src/test/resources/org/citrusframework/yaks/standard/messaging.feature
Use own standard messaging steps to align with other steps provided in YAKS.
> chore: Use YAKS standard steps instead of those provided by Citrus

- script/next_snapshot.sh
- script/set_modules_version.sh
- script/set_version.sh
- script/unsnapshot_olm.sh
- script/unsnapshot_sources.sh
Different OS types for CI and local development require portable scripts.
> fix(#134): Make scripts portable

- README.md
- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpServerSteps.java
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSettings.java
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSteps.java
- java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka-multiline.feature
- java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka.feature
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/SendEventSteps.java
Fixes #141 
- Add step to set producer/consumer properties
- Add step to set the message key
- Add step to set the Kafka topic
- Align steps with other modules saying "send/receive Kafka message"
- Reuse Kafka endpoint from Citrus context (keep consumer offset and enable multiple scenarios to receive messages from a topic)
- Add steps to explicitly set message body and headers (to align with other YAKS modules)
> fix(#141): Set Kafka producer/consumer properties

- examples/knative/knative-eventing.feature
- examples/knative/yaks-config.yaml
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeSettings.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeSupport.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/DeleteKnativeResourceAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/eventing/CreateBrokerAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/eventing/CreateTriggerAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/eventing/VerifyBrokerAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/messaging/CreateChannelAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/messaging/CreateSubscriptionAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/serving/CreateServiceAction.java
- java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/YaksClusterType.java
- java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/YaksSettings.java
- pkg/controller/test/start.go
- Users can set the API version of Knative as environment setting
- Event consumer service selector was using the wrong YAKS domain
- Inject cluster type to YAKS runtime and use different default broker name and url when running on Openshift and Kubernetes respectively
> fix: Knative steps improvements

- README.md
- examples/secrets/credentials.properties
- examples/secrets/delete-secret.sh
- examples/secrets/prepare-secret.sh
- examples/secrets/use-secrets.feature
- examples/secrets/yaks-config.yaml
- java/runtime/yaks-runtime-maven/src/test/java/org/citrusframework/yaks/YaksAutoConfiguration.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ExtensionSettings.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ProjectModelEnricher.java
- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/cmd/config/config.go
- pkg/cmd/test.go
- pkg/controller/test/start.go
- script/package_maven_artifacts.sh
Fixes #123 
Users can add secrets and bind those to tests and named configuration. Tests can use the secret properties as normal test variables. The operator automatically picks up the secrets bound to a test and mounts those as volumes.
> fix(#123): Use secrets for sensitive data

- examples/kamelets/kamelet-binding.feature
- examples/kamelets/kamelet-kafka-binding.yaml
- examples/kamelets/kamelet-knative-binding.yaml
- examples/kamelets/kamelet-uri-binding.yaml
- examples/kamelets/kamelet.feature
- examples/kamelets/timer-source.kamelet.yaml
- java/steps/yaks-camel-k/pom.xml
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/KameletSteps.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/CamelKActionBuilder.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateKameletBindingAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/DeleteKameletBindingAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/VerifyKameletBindingAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/DoneableKameletBinding.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletBinding.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletBindingList.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletBindingSpec.java
- java/steps/yaks-camel-k/src/test/java/org.citrusframework.yaks.camelk/KameletBindingBuilderTest.java
- java/steps/yaks-camel-k/src/test/java/org.citrusframework.yaks.camelk/KameletBuilderTest.java
- java/steps/yaks-camel-k/src/test/resources/kamelet-binding.yaml
- java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.integration.feature
- java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.kamelet.feature
- java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/kamelet-binding.json
- java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/kamelet.json
- java/steps/yaks-camel-k/src/test/resources/timer-source.kamelet.yaml
- java/steps/yaks-kafka/pom.xml
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSettings.java
Let user create/delete/verify KameletBinding custom resources. Provide steps to create KameletBinding specifications with source and sink. Once KameletBinding is created user can verify the ready state of the CR. Steps provide convenient ways to bind a Kamelet to a Kafka topic, a Knative channel or a service URI.
*Create KameletBinding from file resource*
```gherkin
Scenario: Create KameletBinding from file
Given load KameletBinding kamelet-binding.yaml
Then KameletBinding timer-source-binding should be available
```
*bind Kamelet to Knative*
```gherkin
Scenario: Bind Kamelet to Knative
Given KameletBinding source properties
| message  | Hello Knative |
And bind Kamelet timer-source to Knative channel hello-topic of kind InMemoryChannel
When create KameletBinding timer-source-knative
Then …
```
> fix(#148): Add KameletBinding support

- examples/kamelets/kamelet-uri-binding.yaml
- java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpSettings.java
- java/steps/yaks-jms/pom.xml
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/JmsSettings.java
- java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/JmsSteps.java
- java/steps/yaks-jms/src/test/java/org/citrusframework/yaks/jms/JmsBrokerConfiguration.java
- java/steps/yaks-jms/src/test/resources/citrus-application.properties
- java/steps/yaks-jms/src/test/resources/org/citrusframework/yaks/jms/jms-multiline.feature
- java/steps/yaks-jms/src/test/resources/org/citrusframework/yaks/jms/jms.feature
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSettings.java
- java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSteps.java
- java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka-multiline.feature
- Customize consumer timeout
- Predefine message body and headers before send/receive
- Load JMS endpoint from Citrus configuration if present
- Explicitly send/receive from destination
- Adjust steps and wording to to align with other modules (e.g. Kafka)
> fix(#157): Improve JMS steps

- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/cmd/test.go
- pkg/controller/test/noop.go
- pkg/controller/test/test_controller.go
Introduce new test phase updating so operator is not handling test changes anymore. In this phase update the test status and the test spec when updating an existing test. This makes sure to reset the test status properly on the update. Also might fix #74 where status updates and operator changes interfere with each other.
Fixes #159 
Fixes #74
> fix(#159): Reset test status on update

- .github/workflows/nightly.yml
Use separate workflows for pinned and snapshot release on push to master. Do snapshot release for each push on master and use nightly scheduled job for pinned release to reduce amount of artifacts and docker images. Also see if this fixes the issue regarding SNAPSHOT artifacts being referenced in pinned releases.
Relates to #166
> fix(#166): Separate github release workflows and introduce Maven caching

- .github/workflows/nightly.yml
- pkg/cmd/config/config.go
- pkg/cmd/install.go
- pkg/cmd/test.go
- pkg/cmd/util.go
- pkg/controller/test/util.go
Fixes #172 
- Make global operator the default in install
- Global operator also handles temporary namespaces
- Non global operator automatically installing a new operator instance to the temporary namespace
- Verify global operator config and decide which way to go when creating a temporary namespace
> fix(#172): Fix operator setup for temporary namespace

- java/pom.xml
- java/runtime/yaks-runtime-maven/pom.xml
- java/runtime/yaks-runtime-maven/settings/settings_local.xml
- script/package_maven_artifacts.sh
Make sure to load dependencies from local repository first. Using go-offline Maven plugin to grab all required artifacts and plugins in the first place
> chore: Improve S2I image construction

- Makefile
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSupport.java
Plural was not taken correctly.
I've also made the build-image task independent from operator-sdk (which changed command syntax recently).
> Fix kubernetes custom resources

- Makefile
- deploy/olm-catalog/yaks/0.1.0-snapshot/yaks.v0.1.0-snapshot.clusterserviceversion.yaml
- deploy/operator-deployment.yaml
- pkg/util/defaults/defaults.go
- script/util/version_funcs
Using the official citrusframework organization on DockerHub.io. The nightly and SNAPSHOT release builds keep using docker.io/yaks/yaks image though.
> chore: Use the citrusframework organization for pushing Docker images

- java/docs/cli.adoc
- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/cmd/config/config.go
- pkg/cmd/report/junit.go
- pkg/cmd/report/report.go
- pkg/cmd/test.go
- pkg/controller/test/initialize.go
- pkg/controller/test/monitor.go
Fixes #207: Make test timeout configurable
Introduce test status phase "New" and improve error message for tests that hit a timeout.
Fixes #152: Add suite errors to reporting
Do not loose suite related errors (e.g. in prepare scripts) and add those errors to the reporting.
> Make test timeout configurable and add suite errors to reporting

- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletSpec.java
- java/steps/yaks-camel-k/src/test/java/org.citrusframework.yaks.camelk/KameletBuilderTest.java
- java/steps/yaks-camel-k/src/test/resources/timer-source.kamelet.json
When loading Kamelets support unrecognized fields such as x-descriptors set on properties in KameletSpec
Fixes #213
> fix(#213): Do not fail on unrecognized fields in Kamelet model

- java/docs/steps-camel-k.adoc
- java/docs/steps-kamelet.adoc
- java/docs/steps.adoc
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSteps.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/Integration.java
- java/steps/yaks-camel-k/src/test/resources/integration.properties
- java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.integration.feature
Add steps to bind properties to a Camel-K integration. Either set properties in configuration or add property files to the configuration spec.
Fixes #217
> fix(#217): Add support for Camel-K property files

- .github/workflows/snapshot.yml
Enables manual pinned snapshot releases during the day by pushing to branch `snapshot-release`
> chore: Add new GitHub workflow for pinned snapshot release

- .github/workflows/build.yml
- README.md
- examples/extension/README.md
- examples/jitpack/README.md
- examples/kamelets/README.md
- examples/settings/README.md
- java/docs/cli.adoc
- java/docs/configuration.adoc
- java/docs/extensions.adoc
- java/docs/quickstart.adoc
- java/docs/running.adoc
- java/docs/steps-custom.adoc
- pkg/cmd/delete.go
- pkg/cmd/list.go
- pkg/cmd/log.go
- pkg/cmd/report.go
- pkg/cmd/root.go
- pkg/cmd/run.go
Add commands to YAKS CLI
- Delete tests
- List tests
- Watch logs
- Use "run" as alias for "test" command
- Add `--wait` and `--logs` option to run/test command
Fixes #287 
Fixes #288 
Fixes #290
> Add new commands

- java/pom.xml
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeSettings.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeSupport.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/KnativeAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/eventing/CreateBrokerAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/eventing/CreateTriggerAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/messaging/CreateChannelAction.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/messaging/CreateSubscriptionAction.java
- java/steps/yaks-knative/src/test/resources/org/citrusframework/yaks/knative/knative.eventing.feature
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/KubernetesAction.java
- pkg/util/knative/apis.go
- Must use proper Knative group (eventing.knative.dev, messaging.knative.dev) when specifying api versions on resources
- Fix required Knative kinds. Do not require v1beta1 to install Knative roles
- Fix custom namespace setting in Kubernetes and Knative steps
Fixes #293
> fix(#293): Fix Knative apiVersion usage

- examples/custom-resources/README.adoc
- java/docs/steps-kubernetes.adoc
- pkg/apis/yaks/v1alpha1/instance_types_support.go
- pkg/cmd/config/config.go
- pkg/cmd/role.go
- pkg/cmd/run.go
- pkg/controller/test/start.go
- pkg/install/operator.go
- Make sure that the approach is working with both global and non-global YAKS operators
- Add explicit role configuration on yaks-config.yaml in order to support temporary namespaces in combination with non-global operator
> fix(#257): Fix additional roles and role bindings on the YAKS operator

- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/VerifyCustomResourceAction.java
Fixes
```
ava.lang.String,java.lang.String)
Given Kubernetes custom resource event-streaming-kafka-cluster in kafkas.kafka.strimzi.io/v1beta1 is ready # org.citrusframework.yaks.kubernetes.KubernetesSteps.resourceShouldBeReady(java.lang.String,java.lang.String)
com.consol.citrus.exceptions.TestCaseFailedException: Cannot cast java.lang.String to java.lang.Boolean
at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:144)
at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:125)
at org.citrusframework.yaks.kubernetes.KubernetesSteps.resourceShouldMatchCondition(KubernetesSteps.java:299)
at org.citrusframework.yaks.kubernetes.KubernetesSteps.resourceShouldBeReady(KubernetesSteps.java:311)
at ✽.Kubernetes custom resource event-streaming-kafka-cluster in …
```
> Fix verify resource status method

- java/pom.xml
This to try fixing errors with missing Jackson classes when executing tests.
> Add Jackson BOM to align all Jackson sub libraries

- script/cross_compile.sh
- script/util/go_funcs
Excluding "." from the tarball during cross compile
Fixes #322
> fix(#322): Fix yaks tar.gz changes the uid/gid of cwd

- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/IntegrationSpec.java
- java/steps/yaks-camel-k/src/test/java/org.citrusframework.yaks.camelk/IntegrationBuilderTest.java
- java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationActionTest.java
- java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/integration.json
Make sure to set the trait config value type as boolean for "enabled" key. Otherwise, integration will fail during creation.
> fix(#362): Camel K routes with traits config

- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/ReceiveEventSteps.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/SendEventSteps.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/ce/CloudEvent.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/ce/CloudEventMessage.java
- java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/ce/CloudEventSupport.java
- java/steps/yaks-knative/src/test/java/org/citrusframework/yaks/knative/KnativeTestSteps.java
- java/steps/yaks-knative/src/test/resources/org/citrusframework/yaks/knative/knative.event.consumer.feature
Make sure to not expect Ce-Id fields by default when receiving events. Dynamic id values are hard to predict and should be ignored when not specified in expected cloud event data.
> fix(#359): Improve Cloud events send/receive

- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSteps.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/KameletSteps.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/VariableNames.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/CamelKAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/DeleteIntegrationAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/VerifyIntegrationAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/AbstractKameletAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateKameletAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateKameletBindingAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/DeleteKameletAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/DeleteKameletBindingAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/VerifyKameletAction.java
- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/VerifyKameletBindingAction.java
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/VerifyPodAction.java
- java/steps/yaks-kubernetes/src/test/java/org/citrusframework/yaks/kubernetes/KubernetesTestSteps.java
Adding new step `@Given("^Camel K namespace ([^\\s]+)$")` and `@Given("^Kamelet namespace ([^\\s]+)$")`
- Users can use the step to explicitly set the namespace for upcoming Camel K operations. This overwrites the env variable settings in yaks-config.yaml.
- Camel K and Kamelets do have separate namespace settings and steps respectively.
- Fix Kubernetes namespace usage in test actions so steps fully control the namespace to use.
> fix(#368): Add step to explicitly set Camel K namespace

- java/runtime/yaks-runtime-maven/pom.xml
- pkg/controller/test/start.go
- Disable unused plugins
- Call Maven lifecycle phases (test compile, integration test) directly instead of running the whole lifecycle
> chore: Improve mvn runtime startup times

- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSteps.java
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateSecretAction.java
- Add base64 encoding to secret values
- Fix file content handling setting the filename as secret key
- Fix Kubernetes resource name conventions in steps
> fix(#381): Create Kubernetes secret must use base64 encoded values

- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/cmd/config/config.go
- pkg/cmd/run.go
- pkg/controller/test/start.go
Kubedock (use for Testcontainers) and Selenium sidecars use the runAsUser setting provided in yaks-config.yaml
> chore: Make runAsUser configurable

- java/docs/pre-post-scripts.adoc
- pkg/cmd/run.go
- pkg/cmd/run_test.go
- Add `failure()` condition in script execution
- Add test status (SUCCESS, FAILED) indicator as script environment variable
> fix(#316): Indicate test result status in post scripts

- java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/PostgreSQLSteps.java
- pkg/cmd/run.go
- pkg/cmd/util.go
- Make sure to evaluate proper test failure state when creating dumps on failure
- Change startup waiting strategy from logs to listening port as waiting for log output has been flaky in Kubedock setup
> chore: Fix test dumps and PostgreSQL testcontainer waiting strategy

- pkg/apis/yaks/v1alpha1/instance_types_support.go
- pkg/cmd/dump.go
- pkg/cmd/run.go
Make sure to only skip the current test that has errors in pre test scripts. The other tests in the same test group should continue to run as usual.
Fixes #411
> fix(#411): Fix pre test script error handling

- java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationAction.java
- java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationActionTest.java
Allow to set secrets, configmap, properties as runtime configuration via modeline
Fixes #426
> fix(#426): Support config modeline setting on Camel K integration

- .github/workflows/build.yml
- examples/xml/messaging-test.xml
- examples/xml/sample-test.xml
- java/pom.xml
- java/runtime/yaks-runtime-maven/pom.xml
- java/runtime/yaks-runtime-maven/src/test/java/org/citrusframework/yaks/xml/Yaks_IT.java
- java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ProjectModelEnricher.java
- java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/ProjectModelEnricherTest.java
- pkg/apis/yaks/v1alpha1/test_types.go
- pkg/cmd/run.go
- pkg/cmd/util.go
- pkg/controller/test/start.go
- Enable Xml tests in YAKS runtime
- Support *it.groovy and *test.groovy files as test sources
- Support *it.xml and *test.xml files as test sources
Fixes #438
> fix(#438): Add Xml test runtime

- examples/selenium/yaks-config.yaml
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSteps.java
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateAnnotationsAction.java
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateLabelsAction.java
- java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/KubernetesActionBuilder.java
- java/steps/yaks-testcontainers/pom.xml
- java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/LocalStackSteps.java
- java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/MongoDBSteps.java
- java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/PostgreSQLSteps.java
- java/steps/yaks-testcontainers/src/test/java/org/citrusframework/yaks/testcontainers/KubernetesServiceConfiguration.java
- java/steps/yaks-testcontainers/src/test/resources/citrus-application.properties
- pkg/cmd/config/config.go
- pkg/cmd/run.go
- Use Kubernetes client to label kubedock deployment resource after its creation
- Align kubedock and selenium extension configuration
> chore: Label KubeDock containers explicitly

- .github/workflows/build.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/snapshot.yml
- build/Dockerfile
- Use eclipse-temurin:11 base image as adoptopenjdk/openjdk11:slim has been deprecated and is no longer released for linux/amd64
- Use eclipse temurin as Java distribution for github actions
Fixes #456
> fix(#456): Switch operator base image
