citrusframework/yaks

java/pom.xml
java/yaks-testing-jdbc/pom.xml
java/yaks-testing-jdbc/src/test/java/dev/yaks/testing/jdbc/JdbcStepsTest.java
java/yaks-testing-jdbc/src/test/resources/cucumber.properties
java/yaks-testing-jdbc/src/test/resources/dev/yaks/testing/jdbc/jdbc.feature
java/yaks-testing-jdbc/src/test/resources/log4j2-test.xml
java/yaks-testing-jdbc/src/test/resources/test-db-init.sql

#4 Add some unit tests on JDBC verification steps

---

java/yaks-testing-http/src/test/resources/dev/yaks/testing/http/http.client.feature

#5 Add some more unit tests on Http client steps

---

Makefile
README.md
hack/package_maven_artifacts.sh
java/pom.xml
java/yaks-testing-standard/pom.xml
java/yaks-testing-standard/src/main/java/dev/yaks/testing/standard/YaksHelloWorldSteps.java
java/yaks-testing/pom.xml
java/yaks-testing/src/main/java/dev/yaks/testing/TestRunner.java

Fix #9
I've added also a `yaks-testing-standard` lib with just a fancy hello world. Later we may add common things there.

Add user guide

---

deploy/resources.go
deploy/role.yaml
deploy/viewer_role.yaml
java/pom.xml
java/yaks-testing-camel-k/pom.xml
java/yaks-testing-camel-k/src/main/java/dev/yaks/testing/camel/k/CamelKSteps.java
java/yaks-testing-camel-k/src/main/java/dev/yaks/testing/camel/k/model/Integration.java
java/yaks-testing-camel-k/src/test/dev/yaks/testing/camel/k/model/IntegrationBuilderTest.java

Enable to create Camel-K integrations using YAKS.

[ADD] Add new integration step

---

.github/workflows/build.yml
.gitignore
.goreleaser.yml
Makefile
build/Dockerfile.release
deploy/operator.yaml
deploy/resources.go
go.mod
hack/before_release.sh
pkg/cmd/root.go
pkg/cmd/version.go
version/version.go

Setting up continuous delivery

---

examples/helloworld.feature
examples/http.feature
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/report/TestReporter.java
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/report/TestResult.java
java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/report/ReportVerifyPlugin.java
pkg/apis/yaks/v1alpha1/test_types.go
pkg/cmd/report/junit.go
pkg/cmd/report/report.go
pkg/controller/test/evaluate.go

Test reports such as JUnit now using scenario name and full feature file path (as classname)
Fixes #100

fix(#100): Use scenario name in test reports

---

examples/jdbc/yaks-config.yaml
pkg/cmd/config/config.go
pkg/cmd/test.go

fix(#108): Support environment variables in yaks-config.yaml

---

pkg/cmd/uninstall.go

Also uninstall cluster role bindings properly

fix: Uninstall cluster role bindings

---

pkg/apis/yaks/v1alpha1/test_types.go
pkg/client/fastmapper.go
pkg/cmd/operator/operator.go
pkg/cmd/test.go
pkg/controller/test/noop.go
pkg/controller/test/test_controller.go

fix(#164): Create temp namespace in Openshift

---

examples/camel-k/helloworld.groovy
examples/camel-k/integration.feature
examples/camel/camel-route-groovy.feature
examples/camel/camel-route-xml.feature
examples/kamelets/README.md
examples/kamelets/kamelet-resource.feature
examples/kamelets/kamelet.feature
examples/kubernetes/kubernetes.service.feature
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/Integration.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/IntegrationStatus.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/Kamelet.java
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/integration.json

Fixes #165 
Complete integration model with integration status. Also improve examples

fix(#165): Add integration status to model

---

pkg/cmd/test.go

Fix operator deployment into temp workspace

---

.github/workflows/build.yml
examples/camel-k/yaks-config.yaml
examples/kubernetes/yaks-config.yaml

This is using kind + camel k actions (we may add a yaks action as well, for other repos).

Add initial e2e-test for examples

---

script/release.sh

Skip git commit and push if --no-git-push option is set.

fix: Fix git push handling in release

---

script/util/version_funcs

Always use release version given with --release-version setting if it is present.

fix: Fix pinned snapshot release

---

java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletSpec.java

fix(#199): Fix missing authorization field in Kamelet model

---

java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesResource.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSteps.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateResourceAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/DeleteResourceAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/KubernetesActionBuilder.java
java/steps/yaks-kubernetes/src/test/java/org/citrusframework/yaks/kubernetes/KubernetesServiceConfiguration.java
java/steps/yaks-kubernetes/src/test/java/org/citrusframework/yaks/kubernetes/KubernetesTestSteps.java
java/steps/yaks-kubernetes/src/test/resources/org/citrusframework/yaks/kubernetes/kubernetes.resource.feature
java/steps/yaks-kubernetes/src/test/resources/pod.yaml

Add steps to create/delete Kubernetes resources from YAML specs.

fix(#132): Create any Kubernetes resource from YAML

---

deploy/olm-catalog/yaks/0.2.0-snapshot/yaks.v0.2.0-snapshot.clusterserviceversion.yaml
deploy/viewer-role-kubernetes.yaml
deploy/viewer-role-openshift.yaml

OLM installation was missing the permissions on pods/log and pods/status resources
Fixes #209

fix(#209): Fix OLM role permissions

---

java/docs/steps-camel-k.adoc
java/docs/steps-camel.adoc
java/docs/steps-groovy.adoc
java/docs/steps-http.adoc
java/docs/steps-jdbc.adoc
java/docs/steps-jms.adoc
java/docs/steps-kafka.adoc
java/docs/steps-kamelet.adoc
java/docs/steps-knative.adoc
java/docs/steps-kubernetes.adoc
java/docs/steps-openapi.adoc
java/docs/steps-standard.adoc
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/KameletSteps.java
java/steps/yaks-jdbc/src/main/java/org/citrusframework/yaks/jdbc/JdbcSteps.java
java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSteps.java

- Standard steps
- Camel steps
- Camel-K steps
- Kamelet steps
- Groovy steps
- Http steps
- JDBC steps
- JMS steps
- Kafka steps
- Kubernetes steps
- Knative steps
- OpenAPI steps

Add documentation on steps provided by YAKS

---

java/docs/steps-camel.adoc
java/docs/steps-http.adoc
java/docs/steps-jms.adoc
java/docs/steps-kafka.adoc
java/docs/steps-standard.adoc
java/steps/yaks-camel/src/main/java/org/citrusframework/yaks/camel/CamelSteps.java
java/steps/yaks-camel/src/test/resources/body.txt
java/steps/yaks-camel/src/test/resources/org/citrusframework/yaks/camel/camel-route-groovy.feature
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpServerSteps.java
java/steps/yaks-http/src/test/java/org/citrusframework/yaks/http/HttpEndpointConfiguration.java
java/steps/yaks-http/src/test/resources/org/citrusframework/yaks/http/http.client.feature
java/steps/yaks-http/src/test/resources/task.json
java/steps/yaks-jms/src/main/java/org/citrusframework/yaks/jms/JmsSteps.java
java/steps/yaks-jms/src/test/resources/body.json
java/steps/yaks-jms/src/test/resources/org/citrusframework/yaks/jms/jms.feature
java/steps/yaks-kafka/src/main/java/org/citrusframework/yaks/kafka/KafkaSteps.java
java/steps/yaks-kafka/src/test/resources/body.json
java/steps/yaks-kafka/src/test/resources/org/citrusframework/yaks/kafka/kafka.feature
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/StandardSteps.java
java/steps/yaks-standard/src/test/resources/message.txt
java/steps/yaks-standard/src/test/resources/org/citrusframework/yaks/standard/standard.feature
java/steps/yaks-standard/src/test/resources/variables.properties

- Load multiple variables from external property file
- Load single test variable value from external file
- Load message body from external file
Fixes #225

fix(#225): Load test variables from files

---

pkg/apis/yaks/v1alpha1/test_types.go
pkg/cmd/report/junit.go
pkg/cmd/report/report.go
pkg/cmd/test.go

Make sure to include errors in test reports also for those errors raised before the actual test execution.
Fixes #236

fix(#236): Fix error reporting

---

java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/message/CreatesMessage.java
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/message/MessageCreator.java
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/message/MessageCreators.java
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/MessagingSteps.java
java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/message/BarMessageCreator.java
java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/message/PojoMessageCreator.java
java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/standard/EndpointConfiguration.java
java/steps/yaks-standard/src/test/resources/org/citrusframework/yaks/standard/message-creator.feature

Add message creator support coming from Citrus

fix(#238): Port messaging steps from Citrus to YAKS

---

java/pom.xml
java/runtime/yaks-runtime-maven/pom.xml
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeEventingSteps.java
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeMessagingSteps.java
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/ReceiveEventSteps.java
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/KnativeActionBuilder.java
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/actions/eventing/VerifyBrokerAction.java
java/steps/yaks-knative/src/test/java/org/citrusframework/yaks/knative/KnativeServiceConfiguration.java
java/steps/yaks-knative/src/test/java/org/citrusframework/yaks/knative/KnativeTestSteps.java
java/steps/yaks-knative/src/test/resources/org/citrusframework/yaks/knative/knative.event.consumer.feature
java/steps/yaks-knative/src/test/resources/org/citrusframework/yaks/knative/knative.event.producer.feature
java/steps/yaks-knative/src/test/resources/org/citrusframework/yaks/knative/knative.eventing.feature
java/steps/yaks-knative/src/test/resources/org/citrusframework/yaks/knative/knative.messaging.feature

fix(#259): Fix Knative steps

---

java/pom.xml
java/runtime/yaks-runtime-maven/pom.xml
java/steps/yaks-camel-k/src/test/java/org.citrusframework.yaks.camelk/CamelKFeature_IT.java
java/steps/yaks-camel/src/test/java/org/citrusframework/yaks/camel/CamelFeature_IT.java
java/steps/yaks-groovy/src/test/java/org/citrusframework/yaks/groovy/GroovyFeature_IT.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpServerSteps.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpSettings.java
java/steps/yaks-http/src/test/java/org/citrusframework/yaks/http/HttpFeature_IT.java
java/steps/yaks-jdbc/src/test/java/org/citrusframework/yaks/jdbc/JdbcFeature_IT.java
java/steps/yaks-jms/src/test/java/org/citrusframework/yaks/jms/JmsFeature_IT.java
java/steps/yaks-kafka/src/test/java/org/citrusframework/yaks/kafka/KafkaFeature_IT.java
java/steps/yaks-knative/src/test/java/org/citrusframework/yaks/knative/KnativeFeature_IT.java
java/steps/yaks-kubernetes/src/test/java/org/citrusframework/yaks/kubernetes/KubernetesFeature_IT.java
java/steps/yaks-openapi/src/test/java/org/citrusframework/yaks/openapi/OpenApiFeature_IT.java
java/steps/yaks-selenium/src/test/java/org/citrusframework/yaks/selenium/SeleniumFeature_IT.java
java/steps/yaks-standard/src/test/java/org/citrusframework/yaks/standard/StandardFeature_IT.java

Should stabilize the CI build where unit tests and integration tests conflicts happen occasionally

fix: Separate unit and integration test phase with Maven failsafe plugin

---

java/steps/yaks-jdbc/src/main/java/org/citrusframework/yaks/jdbc/JdbcSteps.java
java/steps/yaks-jdbc/src/test/resources/org/citrusframework/yaks/jdbc/jdbc.feature
java/steps/yaks-jdbc/src/test/resources/secrets.properties

fix(#266): Support variables in JDBC database connection steps

---

.github/workflows/build.yml
.github/workflows/nightly.yml
README.md

Use "main" branch as default branch

chore: Rename master branch on GitHub

---

pkg/cmd/test.go
pkg/cmd/util.go
pkg/util/kubernetes/log/annotation_scraper.go

fix(#265): Proper exit code on test errors/failures

---

java/steps/yaks-groovy/src/main/java/org/citrusframework/yaks/groovy/GroovyScriptSteps.java
java/steps/yaks-groovy/src/main/java/org/citrusframework/yaks/groovy/dsl/actions/ActionScript.java
java/steps/yaks-groovy/src/main/java/org/citrusframework/yaks/groovy/dsl/actions/Actions.java
java/steps/yaks-groovy/src/main/java/org/citrusframework/yaks/groovy/dsl/actions/ActionsConfiguration.java
java/steps/yaks-groovy/src/test/resources/actions.groovy
java/steps/yaks-groovy/src/test/resources/org/citrusframework/yaks/groovy/action.script.feature
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/StandardSteps.java
java/steps/yaks-standard/src/test/resources/org/citrusframework/yaks/standard/standard.feature

Use Groovy script to add actions to finally block. Enhance Groovy script execution with multiple supported actions.
Fixes #282

fix(#282): Add doFinally support

---

java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/OpenApiClientSteps.java
java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/OpenApiServerSteps.java
java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/OpenApiTestDataGenerator.java
java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/model/OasModelHelper.java
java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/model/v2/Oas20ModelHelper.java
java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/model/v3/Oas30ModelHelper.java
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-openapi-v2.feature
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-openapi-v3.feature
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-v2.json
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-v3.json
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/standard/StandardSteps.java

- Set optional fields (headers, parameters) via test variables
- Support test variable overwrite in response headers and parameters (query, path)

chore: Improve OpenAPI test data generation

---

java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeSettings.java

fix(#321): Fix Knative broker URL setting on Kubernetes

---

java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSettings.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSteps.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationAction.java
java/steps/yaks-camel-k/src/test/resources/integration.groovy
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.integration.feature

- #319 Load Camel-K integration from file
- #335 Support modeline instructions in Camel-K sources (dependencies, traits)
- #336 Add option to skip test variable support in Camel-K sources

fix: Camel-K step improvements

---

README.md

First "contribution" ever from me. Wanted to try that out.
Delete wrong quote at the licence section

Delete wrong qoute from the license

---

java/docs/steps-camel-k.adoc
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSettings.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSteps.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/CamelKActionBuilder.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/CreateIntegrationAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateKameletAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateKameletBindingAction.java
java/steps/yaks-camel-k/src/test/java/org.citrusframework.yaks.camelk/CamelKTestSteps.java
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.integration.feature
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.kamelet.feature
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/KubernetesActionBuilder.java

Camel K is the official spelling
Fixes #367

fix(#367): Use "Camel K" instead of "Camel-K" in steps

---

java/pom.xml
java/steps/yaks-testcontainers/pom.xml
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/LocalStackSettings.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/LocalStackSteps.java
java/steps/yaks-testcontainers/src/test/resources/amazonKinesisClient.groovy
java/steps/yaks-testcontainers/src/test/resources/amazonS3Client.groovy
java/steps/yaks-testcontainers/src/test/resources/org/citrusframework/yaks/testcontainers/aws-kinesis.feature
java/steps/yaks-testcontainers/src/test/resources/org/citrusframework/yaks/testcontainers/aws-s3.feature
java/tools/maven/yaks-maven-extension/pom.xml

- Support S3 services
- Consolidate AWS SDK versions in project

fix(#371): Add support for LocalStack Testcontainers

---

java/docs/steps-kubernetes.adoc
java/docs/steps-testcontainers.adoc
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeEventingSteps.java
java/steps/yaks-knative/src/main/java/org/citrusframework/yaks/knative/KnativeMessagingSteps.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSteps.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateAnnotationsAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateLabelsAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/KubernetesActionBuilder.java
java/steps/yaks-kubernetes/src/test/resources/org/citrusframework/yaks/kubernetes/create.secret.feature

Fixes #377 
#377: Add labels/annotations on Kubernetes resources
Fixes #378 
#378: Delete Knative broker/channel steps

fix(#377-#378): Add Labels and delete Knative broker/channel

---

java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/LocalStackSettings.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/LocalStackSteps.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/MongoDBSettings.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/MongoDBSteps.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/PostgreSQLSettings.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/PostgreSQLSteps.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/TestContainersSettings.java

Add steps to explicitly set timeout to wait for container to startup

chore: Customize Testcontainers startup timeout

---

pkg/cmd/config/config.go
pkg/cmd/dump.go
pkg/cmd/run.go

Add pod logs to the dump based on custom label selector

fix(#188): Dump pod logs with custom label selector

---

java/pom.xml

- Apache Camel 3.15.0
- Log4j 2.17.2

chore(deps): Bump dependency versions

---

java/steps/yaks-openapi/pom.xml
java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/OpenApiResourceLoader.java
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-openapi-server.feature
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-v3.yaml

fix(#400): Add YAML support for OpenAPI specification

---

java/steps/yaks-openapi/src/main/java/org/citrusframework/yaks/openapi/OpenApiServerSteps.java
java/steps/yaks-openapi/src/test/resources/org/citrusframework/yaks/openapi/petstore-v3.yaml

- Fixes verification in generated OpenAPI receive request steps

fix(#400): Fix double slash in OpenAPI request paths

---

Makefile
config/crd/bases/yaks.citrusframework.org_instances.yaml
config/crd/bases/yaks.citrusframework.org_tests.yaml
config/manifests/bases/yaks.clusterserviceversion.yaml
deploy/olm-catalog/yaks/0.11.0-snapshot/yaks.citrusframework.org_instances.yaml
deploy/olm-catalog/yaks/0.11.0-snapshot/yaks.citrusframework.org_tests.yaml
deploy/olm-catalog/yaks/0.11.0-snapshot/yaks.v0.11.0-snapshot.clusterserviceversion.yaml
helm/yaks/crds/crd-instance.yaml
helm/yaks/crds/crd-test.yaml
java/docs/contributing.adoc
script/add_createdAt.sh
script/docs.sh
script/gen_crd.sh
script/release.sh
script/util/olm_funcs
script/util/version_funcs

Simplify build script maintenance and assume MacOS users to use `gnu-sed`

chore(build): Assume gnu-sed usage for MacOS users

---

pkg/cmd/report/report.go
pkg/cmd/report/util.go
pkg/cmd/run.go
pkg/util/util.go

Make sure to create the dump directory for automatic test dump on run command

chore: Auto create dump directory

---

java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSettings.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSteps.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/integration/VerifyIntegrationAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSettings.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSteps.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/KubernetesActionBuilder.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/VerifyPodAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/WatchPodLogsAction.java

- Watch pod logs for given amount of time
- Print logs while waiting for a specific pod log message

fix(#429): Add watch pod logs action and steps

---

README.md
examples/selenium/yaks-config.yaml
java/pom.xml
java/steps/yaks-standard/src/main/java/org/citrusframework/yaks/YaksSettings.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/LocalStackSteps.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/MongoDBSteps.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/PostgreSQLSteps.java
java/steps/yaks-testcontainers/src/main/java/org/citrusframework/yaks/testcontainers/TestContainersSettings.java
pkg/cmd/run.go
pkg/controller/test/start.go

- Update KubeDock to v0.9.0
- Add labels to visualize connections and icons for testcontainers
- Update Testcontainers to v1.17.4

chore: Label KubeDock containers

---

.github/workflows/build.yml
examples/yaml/sample.test.yaml
java/pom.xml
java/runtime/yaks-runtime-core/pom.xml
java/runtime/yaks-runtime-maven/src/test/java/org/citrusframework/yaks/yaml/Yaks_IT.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ProjectModelEnricher.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/ProjectModelEnricherTest.java
java/tools/yaks-jbang/pom.xml
pkg/language/language.go

Support YAML test source files when running YAKS tests

fix(#455): Add YAML runtime

---

deploy/olm-catalog/yaks/0.14.2/yaks.v0.14.2.clusterserviceversion.yaml
java/pom.xml
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/KameletSteps.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateKameletAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/jbang/CamelJBangSettings.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/Kamelet.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletBindingSpec.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletSpec.java
java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/KameletBindingBuilderTest.java
java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/KameletBuilderTest.java
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/camelk.kamelet.feature
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/kamelet-binding.json
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/kamelet.json
java/steps/yaks-camel-k/src/test/resources/timer-source.kamelet.json
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/KubernetesSupport.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateSecretAction.java
java/steps/yaks-kubernetes/src/main/java/org/citrusframework/yaks/kubernetes/actions/CreateServiceAction.java
java/tools/yaks-jbang/src/main/java/org/citrusframework/yaks/jbang/commands/Run.java
pkg/cmd/config/config.go
pkg/cmd/jbang/jbang.go
pkg/cmd/run.go

- Update Kamelet and KameletBinding model to support data types
- chore: Return proper JBang exit status based on failed tests
- chore: Fix YAKS JBang test file extensions
- chore: Fix Cucumber tags env setting
- chore(deps): Update to Camel 3.20.2

chore: Add support for Kamelet data types

---

examples/kafka/kafka-source-binding.yaml
examples/kamelets/kamelet-binding.feature
examples/kamelets/kamelet.feature
examples/kamelets/timer-to-log-binding.yaml
examples/kamelets/yaks-config.yaml
java/docs/steps-kamelet.adoc
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/CamelKSettings.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/KameletSteps.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/CamelKActionBuilder.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/AbstractKameletAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateBindingAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/DeleteBindingAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/actions/kamelet/VerifyBindingAction.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/Binding.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/BindingList.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/BindingSpec.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/BindingStatus.java
java/steps/yaks-camel-k/src/main/java/org/citrusframework/yaks/camelk/model/KameletBinding.java
java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/BindingBuilderTest.java
java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/actions/kamelet/CreateBindingActionTest.java
java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/actions/kamelet/DeleteBindingActionTest.java
java/steps/yaks-camel-k/src/test/java/org/citrusframework/yaks/camelk/actions/kamelet/VerifyBindingActionTest.java
java/steps/yaks-camel-k/src/test/resources/kafka-source-binding.yaml
java/steps/yaks-camel-k/src/test/resources/kamelet-binding.yaml
java/steps/yaks-camel-k/src/test/resources/org/citrusframework/yaks/camelk/kamelet-binding.json

- Support both KameletBinding and Binding resources for Camel K
- Choose binding resource based on API version v1alpha1 or v1

chore: Support Camel K binding v1

---

java/docs/configuration.adoc
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ExtensionSettings.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/ProjectModelReader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/AbstractConfigFileRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/FileBasedRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/RepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/env/EnvironmentSettingRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/json/JsonFileRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/properties/PropertyFileRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/properties/SystemPropertyRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/main/java/org/citrusframework/yaks/maven/extension/configuration/yaml/YamlFileRepositoryLoader.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/FileBasedPluginRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/FileBasedRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/env/EnvironmentSettingPluginRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/json/JsonFilePluginRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/json/JsonFileRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/properties/PropertyFilePluginRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/properties/PropertyFileRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/properties/SystemPropertyPluginRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/properties/SystemPropertyRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/yaml/YamlFilePluginRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/java/org/citrusframework/yaks/maven/extension/configuration/yaml/YamlFileRepositoryLoaderTest.java
java/tools/maven/yaks-maven-extension/src/test/resources/yaks.properties
java/tools/maven/yaks-maven-extension/src/test/resources/yaks.settings.json
java/tools/maven/yaks-maven-extension/src/test/resources/yaks.settings.yaml
pkg/cmd/config/config.go
pkg/cmd/run.go
pkg/util/envvar/envvar.go

Enable users to define custom Maven plugin repositories
Fixes #477

fix(#477): Support custom Maven plugin repository

---

java/docs/steps-http.adoc
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpServerSteps.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpSettings.java

Enable/disable header name case-insensitive verification mode
Fixes #472

fix(#472): Add Http header name ignore case setting

---

examples/extension/steps/pom.xml
java/steps/yaks-http/pom.xml
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpClientSteps.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpServerSteps.java
java/steps/yaks-http/src/main/java/org/citrusframework/yaks/http/HttpSettings.java
java/steps/yaks-http/src/test/resources/org/citrusframework/yaks/http/http.basic.auth.server.feature
java/steps/yaks-http/src/test/resources/org/citrusframework/yaks/http/http.secure.server.feature

- Enable Http client and server steps to configure and use basic auth method
Fixes #485

fix(#485): Add Http basic auth support
